/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class Library {
    public static void main(String[] args) {

        LinkedList list = new LinkedList();
        list.insert("c");
        list.insert("b");
        list.insert("a");

       System.out.println(list.toString());

       list.includes("a");
        list.includes("emam");

        list.append("e");
        list.append("F");

        System.out.println(list.toString());

        list.insertBefore("b", "a.a");
        list.insertBefore("e", "c.a");
        System.out.println(list.toString());

        list.insertAfter("e", "irbid");
        list.insertAfter("F", "last");

        System.out.println(list.toString());
        System.out.println(list.kthFromEnd(9));


    }

}
