/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class Library {
    public static void main(String[] args) {

        LinkedList list = new LinkedList();
        list.insert("c");
        list.insert("b");
        list.insert("a");

       System.out.println(list.toString());

       list.includes("a");
        list.includes("emam");
    }

}
