/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quicksort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    public void testQuickSort() {

        int[] arr = {8, 4, 23, 42, 16, 15};
        int n = arr.length;
        Library.quickSort(arr, 0, n - 1);
        int[] expArr = {4, 8, 15, 16, 23, 42};
        int[] sortedArr = Library.printToTest(arr);
        assertArrayEquals(expArr,sortedArr);
    }


}
