/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MergeSort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    public void positiveTest() {
        int[] actual = { 5, 1, 6, 2, 3, 4 };
        int[] expected = { 1, 2, 3, 4, 5, 6 };
        Library.mergeSort(actual);
        assertArrayEquals(expected, actual);
    }
}
