/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class Library {
    public static void main(String[] args)
    {

        BinarySearchTree tree = new BinarySearchTree();


//        tree.add(50);
//        tree.add(10);
//        tree.add(60);
//        tree.add(5);
//        tree.add(75);

        System.out.println(tree.preOrder(tree.root));
        System.out.println(tree.inOrder(tree.root));
        System.out.println(tree.postOrder(tree.root));


        System.out.println(tree.max());



    }
}
