/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    public void testEmptyList() {

        LinkedList list = new LinkedList();

        String msg = list.toString();
//        System.out.println(msg);
        assertEquals("Contents:\n" +
                "list is empty :(", msg);

    }

    @Test
    public void testInsert() {

        LinkedList list = new LinkedList();

         list.insert("emam");
        String msg = list.toString();
//        System.out.println(msg);
        assertEquals("Contents:\n" +
                "{emam} -> ", msg);

    }

    @Test
    public void testTrueInclude() {
        LinkedList list = new LinkedList();
        list.insert("emam");
        boolean msg = list.includes("emam");
           assertTrue(msg);

    }

    @Test
    public void testFalseInclude() {
        LinkedList list = new LinkedList();
        list.insert("emam");
        boolean msg = list.includes("someone");
        assertFalse(msg);

    }

    @Test
    public void testAllList() {
        LinkedList list = new LinkedList();
        list.insert("emam");
        list.insert("emam");
        list.insert("emam");
        String msg = list.toString();
//        System.out.println(msg);
        assertEquals("Contents:\n" +
                "{emam} -> {emam} -> {emam} -> ", msg);

    }

    @Test
    public void testAppend() {
        LinkedList list = new LinkedList();
        list.insert("emam");
        list.insert("emam");
        list.insert("emam");
        list.append("someone");
        String msg = list.toString();
  // TESTING FOR MULTIPLE INPUTS
        assertTrue(msg.endsWith("{someone} -> "));
        list.append("else");
        String msg2 = list.toString();
        System.out.println(msg2);
        assertTrue(msg2.endsWith("{else} -> "));
    }



    @Test
    public void testInsertBefore() {
        LinkedList list = new LinkedList();
        list.insert("emam");
        list.insert("ahmed");
        list.insert("ali");
        // MIDDLE
        list.insertBefore("ahmed", "hani");
        String msg = list.toString();
        System.out.println(msg);
        assertEquals("Contents:\n" +
                "{ali} -> {hani} -> {ahmed} -> {emam} -> ", msg);
        // FIRST
        list.insertBefore("ali", "lutfy");
        String msg2 = list.toString();
        System.out.println(msg2);
        assertEquals("Contents:\n" +
                "{lutfy} -> {ali} -> {hani} -> {ahmed} -> {emam} -> ", msg2);

    }


    @Test
    public void testInsertAfter() {
        LinkedList list = new LinkedList();
        list.insert("emam");
        list.insert("ahmed");
        list.insert("ali");
        // MIDDLE
        list.insertAfter("ali", "amman");
        String msg = list.toString();
        System.out.println(msg);
        assertEquals("Contents:\n" +
                "{ali} -> {amman} -> {ahmed} -> {emam} -> ", msg);


    }


}