/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class Library {

    public static void main(String args[])
    {
//        Stack s = new Stack();
//        s.push("10");
//        s.push("20");
//        s.push("30");
//        s.push("40");
//        s.push("50");
//        System.out.print(s.peek() +"\n");
//        s.pop();
//        System.out.print(s.peek() +"\n");
//        s.pop();
//        System.out.print(s.peek() +"\n");
//        s.pop();
//        System.out.print(s.peek() +"\n");
//        s.pop();
//        System.out.print(s.peek() +"\n");
//        s.pop();
//        System.out.print(s.peek() +"\n");
//
//
//Queue q = new Queue();
//
//        q.enqueue("emam");
//        q.enqueue("hadi");
//
//
//     System.out.println(q.dequeue());
//        System.out.println(q.dequeue());
//        System.out.println(q.dequeue());
////        System.out.println(q.dequeue());
//
//        System.out.println( q.peek());

//
//        AnimalShelter shop = new AnimalShelter();
//        shop.enq("dog");
//        shop.enq("dog");
//        shop.enq("dog");
//        shop.enq("dog");
//        shop.enq("cat");
//        shop.enq("cat");
//        shop.enq("cat");
//        shop.enq("cat");
//        shop.enq("fish");
//        shop.enq("Emam");
//
//       System.out.println(shop.deqCat());
//        System.out.println(shop.deqAny());




        String input = "[()]{}{[()()]()}" ;

        System.out.println(BracketValidator.validator(input));


    }


}
