/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hash;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

@Test
    public void addTest() {

    HashTable table = new HashTable();
    table.add(10, 36);
    System.out.println( table.contain(10));
     assertTrue(table.contain(10));
}

    @Test
    public void getTest() {

        HashTable table = new HashTable();
        table.add(10, 36);
        System.out.println( table.get(10));
        String result = table.get(10).toString();
        assertEquals("36", result);
    }

    @Test
    public void get404Test() {

        HashTable table = new HashTable();
        table.add(10, 36);
        System.out.println( table.get(11));
        assertEquals(null,  table.get(11));
    }





}
